### ISSUE TITLE
authentification

### ISSUE THREAD

**Issue by croziors** [brianmiller/phvalheim-server#1] opened 2022-11-10 13:35 UTC
Hello
i just install but i try authentification i have probleme
i use steam 

https://hostname/authenticated.ph

but when i am after steam redirect to my url but don t use port 8080 just use hotname

how i can modifiy for have redirect  https://hostname:8080/authenticated.ph

thx

**Comment by brianmiller** [comment] 2022-11-10 16:24
> Hello i just install but i try authentification i have probleme i use steam
> 
> https://hostname/authenticated.ph
> 
> but when i am after steam redirect to my url but don t use port 8080 just use hotname
> 
> how i can modifiy for have redirect https://hostname:8080/authenticated.ph
> 
> thx

Hello @croziors,

I'm happy to help here. 

Are you using a reverse proxy or sending traffic directly to PhValheim from the internet? 

You should be able to pass a port to the "phvaheimHost" variable on start.  I mentioned in the readme I haven't tried without a reverse proxy+TLS.  I'll go through some tests to see if we run can without it.  For now, try passing the port to the variable mentioned above.
You can see we take whatever you pass to the variable.
https://github.com/brianmiller/phvalheim-server/blob/master/container/nginx/www/public/index.php#L77

**Comment by brianmiller** [comment] 2022-11-10 16:25
My mistake on closing.  I've reopened the issue and will look at it.

**Comment by croziors** [comment] 2022-11-10 17:10
yes i have reserve proxy now but doesnt work
http://valheim.kripy.lu/

Le jeu. 10 nov. 2022 à 17:25, theoriginalbrian ***@***.***> a
écrit :

**Comment by brianmiller** [comment] 2022-11-10 17:31
Oh perfect. That's the right way to do things.  You just need to use the reverse proxy config I have posted in the readme.  

NGINX+Let's Encrypt work nicely together.  Are you experienced with certbot? If so, there's little you need to do other than tell your reverse proxy to use TLS.

Your external port will be 80/443 (to support HTTP->HTTPS redirect.  Port 8080 will be behind your firewall.

**Comment by croziors** [comment] 2022-11-10 17:45
thx work now and second point
You don't have any worlds in your library.


Le jeu. 10 nov. 2022 à 18:31, theoriginalbrian ***@***.***> a
écrit :

**Comment by brianmiller** [comment] 2022-11-10 18:44
Nice!  For the library access, you just need to hit "Edit Citizens" in the admin interface and add the players you want to grant access to (their SteamID number).

This tool helps: 
https://www.steamidfinder.com/

Or you can just grab it from your Steam app.
![image](https://user-images.githubusercontent.com/342276/201179953-91f4f6ad-9920-4c6b-ab37-f8240b4d37ee.png)

**Comment by croziors** [comment] 2022-11-10 18:47
[image: image.png]

Le jeu. 10 nov. 2022 à 19:44, theoriginalbrian ***@***.***> a
écrit :

**Comment by brianmiller** [comment] 2022-11-10 18:56
hmm.. it looks like you tried to post an update, but all I see is [image: image.png].

**Comment by brianmiller** [comment] 2022-11-10 19:03
It looks like I need to add a few things to the readme. Thank you.

Your admin interface will be the server hosting PhValheim (behind the reverse proxy).

E.g.,
Public URL: https://phvalheim.mydomain.tld
Admin interface: http://dockerhost:8080/admin

**Comment by croziors** [comment] 2022-11-10 19:54
So what i need doing i am not sure understand sorry

**Comment by brianmiller** [comment] 2022-11-10 23:15
No worries.

You're almost there. In your admin interface, click on "Edit Citizens" for the world you want to grant access to.  

Add all SteamIDs you want to have access to the world. 

You can find player SteamIDs via the links I posted in my previous comment.

I may add an automatic SteamID in the future.

**Comment by croziors** [comment] 2022-11-11 00:15
But i have nothing in interface
i am available tmr for show you in discord if you want

Le ven. 11 nov. 2022 à 00:15, theoriginalbrian ***@***.***> a
écrit :

**Comment by croziors** [comment] 2022-11-11 12:20
thx

Le ven. 11 nov. 2022 à 03:16, theoriginalbrian ***@***.***> a
écrit :

**Comment by brianmiller** [comment] 2022-11-11 15:35
> What TZ are you in?

**Comment by croziors** [comment] 2022-11-11 15:37
UTC+1

Le ven. 11 nov. 2022 à 16:35, theoriginalbrian ***@***.***> a
écrit :

**Comment by brianmiller** [comment] 2022-11-11 18:21
Can you give me the output of this command from within the container?

/opt/stateful/games/steamcmd/steamcmd.sh +login anonymous +quit

**Comment by brianmiller** [comment] 2022-11-15 02:35
version 1.5 has been pushed to correct this issue

**Comment by brianmiller** [comment] 2022-11-16 16:45
I'm closing this issue has the root cause as been resolved.

**Closed by brianmiller** 2022-11-16 16:45 UTC

**Comment by croziors** [comment] 2023-03-15 18:10
Hello
what is limitation player of server ?
is it possible add password ?
thanks
