### ISSUE TITLE
Unable to Start New World - Missing valheim_server.x86_64 File

### ISSUE THREAD

**Issue by vortexrap** [brianmiller/phvalheim-server#15] opened 2022-11-25 03:35 UTC
Hey there - first off, really appreciate this project! I'm trying it now b/c ive always wanted to do mods but have alot of friends hesitant to try because of the desync/conflicts.

Launching following your Unraid guide, I've tried to start a new server, it creates just fine, but immediately stops after starting.

Engine Logs:
```
Thu Nov 24 22:16:39 EST 2022 [NOTICE : phvalheim] Start command recieved for world 'mistlands':
Thu Nov 24 22:16:42 EST 2022 [ERROR : phvalheim] ERROR: Could not start world 'mistlands', exiting...
```

Digging around, in the supervisor logs, found this error:
`fatal | Exited too quickly (process log may have details) | valheimworld_mistlands`

Expanding the log shows this error:
`
/opt/stateless/games/valheim/scripts/startWorld.sh: 41: exec: /opt/stateful/games/valheim/worlds/mistlands/game/valheim_server.x86_64: not found
`

Checking that directory, I don't see the valheim_server.x86_64 file.

Did I miss a step to get this server file added to the directory? Is there potentially something wrong here when trying to download valheim server binaries via Steam CMD (at least that's my assumption in how the dedicated server is grabbed)?

**Comment by Maxver0** [comment] 2022-11-29 05:24
There are no extra steps besides just creating a new world on the /admin/ page. I was able to create multiple worlds with mods with no file issues like you're having. I am using unraid 6.11 as well.

**Comment by brianmiller** [comment] 2022-11-29 17:01
I suspect the file is missing because it couldn't download it.  At first glance, I suspect DNS isn't being passed to the container on start.  

try adding "--dns 8.8.8.8 --dns 8.8.4.4" do your extra parameters on start.

**Comment by brianmiller** [comment] 2022-12-29 19:31
Duplicate of #3

I'll leave this open until I close #3 and validate.

**Comment by brianmiller** [comment] 2023-11-08 20:35
Closing this as our dependency on DNS in this context has been removed.

**Closed by brianmiller** 2023-11-08 20:35 UTC
Labels: bug, duplicate
